In [10]:
import numpy as np
import pandas as pd

In [11]:
data=({'Brand':["Tata","VW","VW","Honda","Tata","Toyota","Toyota"],
     'Price':[12,14,11,15,21,15,13]})
df=pd.DataFrame(data)
print(df)

    Brand  Price
0    Tata     12
1      VW     14
2      VW     11
3   Honda     15
4    Tata     21
5  Toyota     15
6  Toyota     13

In [12]:
def ordinal_encode(df):
    df['Brand']=df['Brand'].map({'Tata':0,'VW':1,'Honda':2, 'Toyota':3})
    return df
df=ordinal_encode(df)
print(df)

   Brand  Price
0      0     12
1      1     14
2      1     11
3      2     15
4      0     21
5      3     15
6      3     13